JakeWharton/dagger-reflect

integration-tests/src/main/java/com/example/BuilderDependency.java, integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java, reflect/src/main/java/dagger/reflect/ReflectiveComponentParser.java, reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java
Didn't add tests for all the type hierarchy walking stuff
=> Add support for component dependencies

integration-tests/src/main/java/com/example/ModuleClass.java, integration-tests/src/main/java/com/example/ModuleClassAndInterfaceDuplicatesHierarchy.java, integration-tests/src/main/java/com/example/ModuleClassAndInterfaceHierarchy.java, integration-tests/src/main/java/com/example/ModuleClassHierarchy.java, integration-tests/src/main/java/com/example/ModuleClassHierarchyStatics.java, integration-tests/src/main/java/com/example/ModuleInterface.java, integration-tests/src/main/java/com/example/ModuleInterfaceHierarchy.java, integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java
=> Allow @Modules to be interfaces

build.gradle, reflect-compiler/src/main/java/dagger/reflect/compiler/DaggerReflectCompiler.java, reflect/src/main/java/dagger/reflect/BindingGraph.java, reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java, reflect/src/test/java/dagger/reflect/BindingGraphTest.java
NullAway is still only set to warn, for now…
=> Add error-prone and NullAway

integration-tests/src/test/java/com/example/IntegrationTest.java, integration-tests/src/test/java/com/example/OptionalBindingNullable.java, reflect/src/main/java/dagger/reflect/Binding.java
This is forbidden at compile-time by Dagger.
=> Add test for optional of nullable

integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/BindingMap.java, reflect/src/main/java/dagger/reflect/LinkedMapBinding.java, reflect/src/main/java/dagger/reflect/Reflection.java, reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java, reflect/src/main/java/dagger/reflect/UnlinkedMapBinding.java, reflect/src/main/java/dagger/reflect/UnlinkedSetBinding.java
Need a test for `unwrapValue=false` but that can come later.
=> Add support for @IntoMap

integration-tests/src/test/java/com/example/IntegrationTest.java
=> Enable elements into set via binds test for reflect backend

.travis.yml, build.gradle, codegen/build.gradle, integration-tests/android/build.gradle, integration-tests/android/src/main/AndroidManifest.xml, integration-tests/android/src/main/java/com/example/AppComponent.java, integration-tests/android/src/main/java/com/example/ExampleActivity.java, integration-tests/android/src/main/java/com/example/ExampleApp.java, integration-tests/android/src/main/java/com/example/StringModule.java, integration-tests/android/src/test/java/com/example/ExampleActivityTest.java, reflect-compiler/build.gradle, settings.gradle
Right now this doesn't do much, but it will host more in the future.
=> Add integration test for Android

integration-tests/src/main/java/com/example/SubcomponentBuilderProvision.java, integration-tests/src/main/java/com/example/SubcomponentProvision.java, integration-tests/src/test/java/com/example/AbstractBuilderClass.java, integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java, reflect/src/main/java/dagger/reflect/DaggerReflect.java, reflect/src/main/java/dagger/reflect/ReflectiveComponentBuilderParser.java, reflect/src/main/java/dagger/reflect/ReflectiveComponentParser.java, reflect/src/main/java/dagger/reflect/Scope.java
Subcomponent builder provisions are supported and subcomponent provision provided it doesn't require any module instances.
=> Add support for simple subcomponent provision and scope hierarchy

reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java, reflect/src/main/java/dagger/reflect/JustInTimeLookup.java, reflect/src/main/java/dagger/reflect/LinkedInstanceBinding.java, reflect/src/main/java/dagger/reflect/ReflectiveComponentParser.java, reflect/src/main/java/dagger/reflect/Scope.java
This hides the implementation of parsing from those who need to build a scope.
=> Add a Scope.Builder

build.gradle, gradle/wrapper/gradle-wrapper.properties
Gradle 5.2.1 bump plus others.
=> Bump versions of dependencies.

integration-tests/src/test/java/com/example/MembersInjectionAbstractMethod.java, integration-tests/src/test/java/com/example/MembersInjectionInterfaceMethod.java, integration-tests/src/test/java/com/example/MembersInjectionPrivateField.java, integration-tests/src/test/java/com/example/MembersInjectionPrivateMethod.java, integration-tests/src/test/java/com/example/MembersInjectionStaticField.java, integration-tests/src/test/java/com/example/MembersInjectionStaticMethod.java
This will be validated soon...
=> Add missing @Module annotations

build.gradle
=> Add NullAway Gradle plugin

integration-tests/src/main/java/com/example/SubcomponentFactoryProvision.java, integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentFactoryInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentScopeBuilder.java, reflect/src/main/java/dagger/reflect/Reflection.java, reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java
Pull out some reflection helpers as well.
=> Add support for Subcomponent.Factory provision methods

.gitmodules, build.gradle, integration-tests/upstream/build.gradle, reflect/build.gradle, settings.gradle
Right now only 1 test works... but it's a start.
Closes #86.
=> Add upstream Dagger as a submodule and run its functional tests

build.gradle, integration-tests/upstream/build.gradle
Also ensure the submodule is always kept up-to-date with the dependency.
=> Dagger 2.22.1

integration-tests/src/main/java/com/example/LazyScopedBinding.java, integration-tests/src/main/java/com/example/LazyUnscopedBinding.java, integration-tests/src/main/java/com/example/ProviderScopedBinding.java, integration-tests/src/main/java/com/example/ProviderUnscopedBinding.java, integration-tests/src/test/java/com/example/IntegrationTest.java
=> Add tests for Lazy and Provider.

integration-tests/src/test/java/com/example/IntegrationTest.java, integration-tests/upstream/build.gradle, reflect/src/main/java/dagger/reflect/LinkedLazyBinding.java, reflect/src/main/java/dagger/reflect/LinkedProviderBinding.java, reflect/src/main/java/dagger/reflect/Reflection.java, reflect/src/main/java/dagger/reflect/Scope.java, reflect/src/main/java/dagger/reflect/ScopeKeyedLazy.java, reflect/src/main/java/dagger/reflect/ScopeKeyedProvider.java
=> Add support for Provider and Lazy injection

build.gradle
Also lazily configure test tasks.
=> Bump dependency versions, remove snapshot maven repo.

integration-tests/src/main/java/com/example/ComponentBindingInstance.java, integration-tests/src/main/java/com/example/SubcomponentBindingInstance.java, integration-tests/src/test/java/com/example/IntegrationTest.java
=> Fill out more tests for component self-binding

integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentFactoryInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java, reflect/src/main/java/dagger/reflect/ComponentScopeBuilder.java, reflect/src/main/java/dagger/reflect/LinkedLateInstanceBinding.java
=> Add component instance binding

integration-tests/android/src/main/java/com/example/ExampleActivity.java, integration-tests/android/src/test/java/com/example/ExampleActivityTest.java, reflect/src/main/java/dagger/reflect/ComponentScopeBuilder.java, reflect/src/main/java/dagger/reflect/ReflectiveAndroidInjector.java
Update test case to cover this case.
Closes #140.
=> Consider included modules when parsing modules of ContributesAnroidInjector annotation

integration-tests/src/test/java/com/example/BindsElementsIntoSetWrongReturn.java, integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java, reflect/src/main/java/dagger/reflect/Scope.java
There were also duplicate error messages so I removed the redundant
error message and made it more clear exactly what the error is.
=> Improve error message for incorrect return type with BindsIntoSet.

reflect/src/main/java/dagger/reflect/ComponentScopeBuilder.java, reflect/src/main/java/dagger/reflect/Scope.java
Scope should not know about modules or dependency objects.
=> Extract reflective parsing to Scope callers

integration-tests/src/main/java/com/example/MultipleInterfacesRequestSameDependency.java, integration-tests/src/test/java/com/example/IntegrationTest.java, reflect/src/main/java/dagger/reflect/ReflectiveDependencyParser.java
The added test displays the missing behavior.
=> Allow multiple interfaces to request same dependency.

integration-tests/src/main/java/com/example/MultibindingMapEmpty.java, integration-tests/src/main/java/com/example/MultibindingSetEmpty.java, integration-tests/src/test/java/com/example/IntegrationTest.java, integration-tests/src/test/java/com/example/MultibindsAnnotationWrongType.java, reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java, reflect/src/main/java/dagger/reflect/Scope.java
=> Add support for @Multibinds annotation

integration-tests/src/main/java/com/example/MemberInjectorComponent.java, integration-tests/src/main/java/com/example/MemberInjectorGenericType.java, integration-tests/src/main/java/com/example/MemberInjectorInjected.java, integration-tests/src/test/java/com/example/IntegrationTest.java, integration-tests/src/test/java/com/example/MemberInjectorWildcardType.java, integration-tests/src/test/java/com/example/MembersInjectionWrongReturnType.java, integration-tests/upstream/build.gradle, reflect/src/main/java/dagger/reflect/ComponentScopeBuilder.java, reflect/src/main/java/dagger/reflect/JustInTimeLookup.java, reflect/src/main/java/dagger/reflect/MembersInjectorJustInTimeFactory.java, reflect/src/main/java/dagger/reflect/Scope.java, reflect/src/main/java/dagger/reflect/UnlinkedMembersInjectorBinding.java
=> Add support for MembersInjector
