JakeWharton/dagger-reflect

reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java
reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java
reflect/src/test/java/dagger/reflect/ComponentBuilderInvocationHandlerTest.java
reflect/src/test/java/dagger/reflect/ComponentInvocationHandlerTest.java

Not exactly the same message, but close. The method signature has `.` separators in dagger-compile and `$` separators in dagger-reflect.

Line up and test error messages in components/builders

---

build.gradle
reflect/src/main/java/dagger/reflect/Binding.java
reflect/src/main/java/dagger/reflect/BindingGraph.java
reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java
reflect/src/main/java/dagger/reflect/ReflectiveComponentParser.java
reflect/src/main/java/dagger/reflect/ReflectiveJustInTimeProvider.java
reflect/src/main/java/dagger/reflect/ReflectiveMembersInjector.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java
reflect/src/test/java/dagger/reflect/BindingGraphTest.java

This removes the need to special case optional bindings inside the graph. Instead, the unlinked optional binding can request its dependency key as being optional. Optional keys which are not found will be null in the linked binding array.
Mostly renames in the code. The only interesting bit is in Binding and BindingGraph.

Model optional keys during binding linking

---

.gitignore

My IDEA keeps re-creating this file, hoping to get rid of this annoyance.

Ignore Android's local.properties added by IDEA 2018.x

---

.travis.yml
reflect-compiler/build.gradle

Quick googling revealed that tools.jar was removed in Java 9, this PR was tested via `gradlew clean check jar` on
* java-1.8.0_121-x64-jdk
* java-9.0.1_11-x64-jdk
* java-10.0.2-x64-jdk
* java-11.0.2-x64-jdk
with the change: 8, 9, 10, 11 all produce the same successful Gradle output
without the change: 8 compiles, 9, 10, 11 produces the following Gradle configuration failure:
```
P:\projects\contrib\github-dagger2-reflect>gradlew -S
FAILURE: Build failed with an exception.
* Where:
Build file 'P:\projects\contrib\github-dagger2-reflect\reflect-compiler\build.gradle' line: 16
* What went wrong:
A problem occurred evaluating project ':reflect-compiler'.
> java.lang.NullPointerException (no error message)
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating …
```

Allow compilation on Java 9+

---

integration-tests/src/main/java/com/example/MemberInjectionEmptyAbstract.java
integration-tests/src/main/java/com/example/MemberInjectionEmptyInterface.java
integration-tests/src/main/java/com/example/MemberInjectionInterface.java
integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/ReflectiveMembersInjector.java

Addressing https://github.com/JakeWharton/SdkSearch/pull/149#issuecomment-447603817
Same fix as https://github.com/JakeWharton/dagger-reflect/pull/13/files#diff-7b2e80eb160305e528b1087494445263R25, but no need to walk super-interfaces, just let it pass through the method.

Allow injecting into empty abstract class and interface

---

integration-tests/src/main/java/com/example/BindsProvider.java
integration-tests/src/main/java/com/example/ModuleClassAndInterfaceDuplicatesHierarchy.java
integration-tests/src/main/java/com/example/ModuleClassAndInterfaceHierarchy.java
integration-tests/src/main/java/com/example/ModuleClassHierarchy.java
integration-tests/src/main/java/com/example/ModuleInterface.java
integration-tests/src/main/java/com/example/ModuleInterfaceHierarchy.java
integration-tests/src/test/java/com/example/IntegrationTest.java

```
@SuppressWarnings("UndefinedEquals") // comparing `@Binds CharSequence provided(String)` to `String`
```
could be an alternative solution, but then other newer violations may be hidden and actually give a false-positive pass
The current PR approach of adding a cast is good both ways:
* if it's unnecessary IDEA's `RedundantCast` kicks in
* if cast is not there `UndefinedEquals` shows up again

Fix errorprone UndefinedEquals violations

---

build.gradle

This fixes an error-prone warning about useless parenthesis.

Update auto-value to 1.6.3

---

reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java
reflect/src/main/java/dagger/reflect/ReflectiveDependencyParser.java

This is a more accurate description of the functionality. Especially since I plan to introduce a component parser to generalize component/subcomponent handling.

Rename component parser to dependency parser

---

integration-tests/src/main/java/com/example/ImplicitFinalModules.java
integration-tests/src/test/java/com/example/IntegrationTest.java

Right now the reflection backend fails with 
`java.lang.IllegalStateException: com.example.ImplicitFinalModules.Module1 must be set`
However it should not as the module is no-arg and dagger parses it fine.
I ran into this scenario when testing dagger-reflect with my audiobook player and this is the commit that fixed it: https://github.com/PaulWoitaschek/Voice/commit/40e6daf20619470e599bcab29154bb45953adb81

Added an integration test for a final module

---

build.gradle
integration-tests/build.gradle
integration-tests/src/test/java/com/example/AbstractBuilderClass.java
integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java
reflect/src/main/java/dagger/reflect/ReflectiveComponentBuilderParser.java

This requires using a snapshot build, for now. Once released in 2.22 we will go back to depending on a fixed version.

Check for Builder annotations now that they have runtime retention

---

reflect/src/main/java/dagger/reflect/BindingMap.java
reflect/src/main/java/dagger/reflect/ComponentBuilderInvocationHandler.java
reflect/src/main/java/dagger/reflect/JustInTimeBindingFactory.java
reflect/src/main/java/dagger/reflect/Linker.java
reflect/src/main/java/dagger/reflect/ReflectiveComponentParser.java
reflect/src/main/java/dagger/reflect/ReflectiveJustInTimeBindingFactory.java
reflect/src/main/java/dagger/reflect/Scope.java

This is in prepartion for honoring scope annotations. If the JIT binding factory loads a class which is scoped we'll need to traverse the hierarchy to find which scope to add it to.

Move JIT binding lookup to Scope

---

integration-tests/src/main/java/com/example/Scoped.java
integration-tests/src/test/java/com/example/IntegrationTest.java
integration-tests/src/test/java/com/example/ScopedWrong.java
reflect/src/main/java/dagger/reflect/BindingMap.java
reflect/src/main/java/dagger/reflect/ReflectiveDependencyParser.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java
reflect/src/main/java/dagger/reflect/Scope.java

This allows the parsers to validate the scoping annotations of the bindings they're creating.

Parse into the Scope.Builder to honor scopes

---

integration-tests/src/main/java/com/example/ModulePrivateMethod.java
integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

We have a couple of private helper methods in our modules.
This changes the behavior to allow private methods in modules if and
only if they have no annotations.
An alternative is to keep a blacklist of annotations which are not allowed
on private methods such as `@Provides`?

Allow private helper methods in modules.

---

integration-tests/src/main/java/com/example/JustInTimeDependsOnJustInTime.java
integration-tests/src/test/java/com/example/IntegrationTest.java

This adds a test for when a JustInTime binding has a
dependency on a JustInTime binding.

Add test for JustInTime binding depending on a JustInTime binding.

---

reflect/src/main/java/dagger/reflect/Binding.java
reflect/src/main/java/dagger/reflect/ComponentInvocationHandler.java
reflect/src/main/java/dagger/reflect/ReflectiveMembersInjector.java
reflect/src/main/java/dagger/reflect/Scope.java

We are going to start handling requests for `Provider<T>` soon and this will be confusing. A `LinkedBinding<Provider<T>>` would be a `Provider<Provider<T>>` then and I don't want to get caught up in accidentally interpreting the `LinkedBinding` itself as a `Provider` which it is not (providers should link lazily).

Change LinkedBinding to not be a Provider

---

build.gradle
reflect-compiler/build.gradle
reflect-compiler/src/main/java/dagger/reflect/compiler/DaggerReflectCompiler.java

This prevents leaking the auto-service dependencies into the classpath. And as a result, switch to JetBrains' annotations since we previously used JSR305 ones added transitively from auto-service.

Use auto-service-annotations for compiling

---

build.gradle
integration-tests/src/test/java/com/example/MembersInjectionAbstractMethod.java
integration-tests/src/test/java/com/example/MembersInjectionInterfaceMethod.java

Suppress locally at usage sites where we're expicitly testing this behavior.

Don't suppress a valid EP check globally

---

integration-tests/upstream/build.gradle

Two commits with different ancestors allowed these failing tests to make it to master.

Exclude more functional tests

---

integration-tests/src/main/java/com/example/ReusableScoped.java
integration-tests/src/test/java/com/example/IntegrationTest.java
integration-tests/upstream/build.gradle
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

Right now we actually do nothing and simply create an unscoped binding. This is open to change in the future as the reusable scope offers no guarantees.

Add trivial support for reusable scope

---

integration-tests/src/main/java/com/example/MultibindingMapPrimitiveKey.java
integration-tests/src/main/java/com/example/MultibindingMapPrimitiveValue.java
integration-tests/src/main/java/com/example/MultibindingSetElementsPrimitive.java
integration-tests/src/main/java/com/example/MultibindingSetPrimitive.java
integration-tests/src/main/java/com/example/OptionalBindingPrimitive.java
integration-tests/src/main/java/com/example/OptionalGuavaBindingAbsent.java
integration-tests/src/main/java/com/example/OptionalGuavaBindingPrimitive.java
integration-tests/src/test/java/com/example/IntegrationTest.java
integration-tests/upstream/build.gradle
reflect/src/main/java/dagger/reflect/Key.java
reflect/src/main/java/dagger/reflect/Reflection.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

This can occur for Optional bindings, Set bindings, and Map bindings.

Ensure that primitives are boxed when put in parameterized types

---

reflect/src/main/java/dagger/reflect/Scope.java

This isn't the nice scope chain that we want, but at least it prints our
the missing key, which is bettter than nothing. It also prints out the
linker to know if was null or not.

Have a slightly better error message when unable to find a jit binding.

---

reflect/src/main/java/dagger/reflect/Key.java

Otherwise created types cannot be compared properly.

Key should canonicalize Type input.

---

integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/Reflection.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

Not sure if this is the best way to fix this, but it works. This basically makes the Reusable annotation ignored for the purposes of dagger reflect.

Fix reusable just in time scoping.

---

reflect/src/main/java/dagger/reflect/Binding.java
reflect/src/main/java/dagger/reflect/UnlinkedMapOfProviderBinding.java

This avoids a needless wrapper for map bindings.

Make LinkedBinding a Provider

---

integration-tests/src/test/java/com/example/IgnoreCodegen.java
integration-tests/src/test/java/com/example/IntegrationTest.java
integration-tests/src/test/java/com/example/IntegrationTestRule.java
integration-tests/src/test/java/com/example/ReflectBug.java

This lets us actually validate that expected-failing reflection tests are actually failing.

Use annotations instead of methods to ignore integration tests

---

integration-tests/src/main/java/com/example/MultibindingMapClassKey.java
integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

Fixes https://github.com/JakeWharton/dagger-reflect/issues/132
Problem: wrong key for multibindings with class keys. The key has a value of `java.util.Map<java.lang.Class, com.example.I>` when it should be `java.util.Map<java.lang.Class<?>, com.example.I>`.
Solution: fix `ReflectiveModuleParser`: use generic return type when constructing `entryKeyType`.

Fix generating bindings for multibindings with class keys.

---

integration-tests/src/test/java/com/example/BindsProviderNullabilityMismatch.java
integration-tests/src/test/java/com/example/IntegrationTest.java

When there is a mismatch in nullability between the binding and the request, dagger
throws an exception during compile time. We should throw the same
exception at runtime for Dagger Reflect.
The message should be something like:
```String is not nullable, but is being provided by @Provides @Nullable String com.example.BindsProviderNull.Module1.provideString()```

Add test for nullability mismatch.

---

integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

Dagger error:
> [Dagger/IncompatiblyScopedBindings] `com.example.ScopedWrong` scoped with `@Singleton` may not reference bindings with different scopes:
> `@Provides @com.example.ScopedWrong.Unrelated Object com.example.ScopedWrong.Module1.value()`
Reflect error:
> [Dagger/IncompatiblyScopedBindings] (sub)component scoped with [`@javax.inject.Singleton()`] may not reference bindings with different scopes:
> `@com.example.ScopedWrong.Unrelated @Provides[com.example.ScopedWrong$Module1.value(…)]`

Add IncompatiblyScopedBindings message

---

integration-tests/src/test/java/com/example/BindsElementsIntoSetGenericWrongReturn.java
integration-tests/src/test/java/com/example/IntegrationTest.java
reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java

This improves the error message for more cases when using `@BindsIntoSet`.
This copies the error message from dagger.
See https://github.com/google/dagger/blob/f9e41bc94701c52c60c534390b59b135444276a4/java/dagger/internal/codegen/BindingElementValidator.java#L101

Improve error message for incorrect return types.

---

reflect/src/main/java/dagger/reflect/TypeUtil.java

The GenericArrayTypeImpl constructor will defensively canonicalize as well.

Remove double canonicalization

---

integration-tests/upstream/build.gradle
reflect/src/main/java/dagger/reflect/ScopeBindingProvider.java
reflect/src/main/java/dagger/reflect/UnlinkedMapOfProviderBinding.java

Previously we linked them when the map was linked. But we only need the map to be linked to capture the scope. The map's providers of values should still be late-linked upon first access.
Closes #175. cc @alexjlockwood

Do not eagerly link providers in a map binding
